#!/bin/sh
#
# $Id: config 9688 2013-08-10 00:30:05Z NiLuJe $
#

# WARNING: Take note that we're essentially a shell script, se we absolutely *MUST* use UNIX line endings!
# WARNING: To avoid leaving your system in an undefined state,
#          do *NOT* modify this file while usb over ethernet is enabled!
#          (That means when the the auto enable feature is in use, too!)

# Tweak this to your liking (IPv4 only, no hostname aliases)
KINDLE_IP=192.168.15.244

# Allow SSH over WiFi
# NOTE: If you set this to true, the SSHD *WILL* check your passwords!
# Make sure you know your root password, or auth via shared keys!
USE_WIFI="false"

# Don't switch to Ethernet over USB, and only launch SSHD
# NOTE: Make sure you're able to properly login over SSH before enabling this...
# It's obviously only useful with WiFi devices, so leave to false on non-WiFi devices
USE_WIFI_SSHD_ONLY="false"

# Use OpenSSH instead of dropbear (somewhat faster login)
# NOTE: OpenSSH *WILL* check your passwords!
# Make sure you know your root password, or auth via shared keys!
USE_OPENSSH="false"

# Don't let dropbear print the banner at each login
QUIET_DROPBEAR="false"

# Use a custom NIC field for the MAC adresses.
# Will mostly be of use to people needing to plug multiple Kindles on the same computer/network.
TWEAK_MAC_ADDRESS="false"
